services:
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: Password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  patient-service:
    build: .
    container_name: patient-service
    depends_on:
      patient-service-db:
        condition: service_healthy
    ports:
      - "4000:4000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: Password
